version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: "/plugins/typescript"
    schedule:
      interval: weekly
    groups:
      npm-deps:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: "/plugins/python"
    schedule:
      interval: weekly
    groups:
      pip-deps:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
